version: "3.7"

services:
  api:
    image: local/demo-mtls-api
    build: api

  mtls-sidecar:
    image: local/demo-mtls-sidecar
    build: sidecar
    ports:
      - 443:443
    environment:
      - PROXY_PASS=api:8080
      - ALLOWED_CERTIFICATE_FINGERPRINT=all
