version: "3.7"

services:
  api:
    image: local/demo-mtls-api
    build: api
    ports:
      - 8888:8080

  mtls-sidecar:
    image: local/demo-mtls-sidecar
    build: sidecar
    ports:
      - 443:443
    environment:
      - PROXY_PASS=api:8080
      - ALLOWED_SSL_CLIENT_S_DN='CN=mTLS Teste Client000000001,OU=Lab,O=Alice Ltd,L=Dream,ST=Sandman,C=WL'
