version: "3.7"

services:
  mtls-sidecar:
    image: local/api-mtls-sidecar-server
    build: .
    environment:
      - ALLOWED_SSL_CLIENT_S_DN=all
      # - ALLOWED_SSL_CLIENT_S_DN=CN=mTLS Teste Client000000001,OU=Lab,O=Alice Ltd,L=Dream,ST=Sandman,C=WL
      - PROXY_PASS=https://api.mocki.io:443/v1/13f44462
    volumes:
      - ./example/sidecar/server-certs:/etc/nginx/conf.d/certs
      # - ./temp/generated:/etc/nginx/conf.d/certs
    ports:
      - 443:443
