version: "3.7"

services:
  mtls-sidecar:
    image: local/api-mtls-sidecar-proxy:0.0.2
    build: .
    environment:
      - ALLOWED_CERTIFICATE_FINGERPRINT=all
      - PROXY_PASS=https://mtls.run/
    volumes:
      - ./example/sidecar/server-certs:/etc/nginx/conf.d/certs
    ports:
      - 443:443
